---
- name: Testing andrewrothstein.buildkit
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'buildctl --version'
      ansible.builtin.command: /usr/local/bin/buildctl --version
      changed_when: false
      register: buildkit_test_output
    - name: Output of 'buildctl --version'
      ansible.builtin.debug:
        msg: '{{ buildkit_test_output.stdout }}'
