---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - command: /usr/local/bin/buildctl --version
      register: buildkit_test_output
    - name: buildctl --version
      debug:
        msg: '{{ buildkit_test_output.stdout }}'
