---
- name: Installing andrewrothtein.unarchivedeps
  ansible.builtin.include_role:
    name: andrewrothstein.unarchivedeps
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Check for installation in {{ buildkit_install_dir }}
  become: true
  ansible.builtin.stat:
    path: '{{ buildkit_install_dir }}'
  register: buildkit_binary
  changed_when: false
- name: Downloading and installing buildkit
  when: not buildkit_binary.stat.exists
  block:
    - name: Downloading {{ buildkit_url }}...
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ buildkit_url }}'
        dest: '{{ buildkit_tmp_archive }}'
        checksum: '{{ buildkit_checksum }}'
        mode: '644'
    - name: Mkdir -p {{ buildkit_install_dir }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ buildkit_install_dir }}'
        state: directory
        mode: '755'
    - name: Unarchive {{ buildkit_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ buildkit_tmp_archive }}'
        dest: '{{ buildkit_install_dir }}'
        creates: '{{ buildkit_bin_dir }}'
  always:
    - name: Rm -f {{ buildkit_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ buildkit_tmp_archive }}'
        state: absent
- name: Linking executables in {{ buildkit_bin_dir }} to {{ buildkit_install_dir }}
  become: true
  become_user: root
  with_items: '{{ buildkit_apps }}'
  ansible.builtin.file:
    src: '{{ buildkit_bin_dir }}/{{ item }}'
    dest: '{{ buildkit_link_dir }}/{{ item }}'
    state: link
- name: Linking qemu executables in {{ buildkit_bin_dir }} to {{ buildkit_install_dir }}
  when: item != ansible_architecture
  with_items: '{{ buildkit_qemu_architectures }}'
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ buildkit_bin_dir }}/buildkit-qemu-{{ item }}'
    dest: '{{ buildkit_link_dir }}/buildkit-qemu-{{ item }}'
    state: link
